# Legacy exploratory figure script retained for reference.
# Final manuscript figures are generated by R/13_make_figures_2_to_6_refined.R
source("R/_shared.R")
load_or_install(c("ggplot2", "patchwork", "pheatmap", "ggrepel"))

# Figure 1: study overview
cohorts <- readr::read_csv("results/tables/Table_1_cohort_characteristics.csv", show_col_types = FALSE)
p1 <- cohorts %>%
  dplyr::mutate(group = paste(study, disease_group, sep = " | ")) %>%
  ggplot(aes(x = study, y = n, fill = disease_group)) +
  geom_col(position = "stack") +
  theme_minimal(base_size = 12) +
  labs(title = "Figure 1. Cohort overview", x = NULL, y = "Samples")

save_plot_pdf(p1, "results/figures/Figure_1_study_overview.pdf", width = 8, height = 5)

# Figure 3: meta-analysis summary
meta_tbl <- readr::read_csv("data/processed/meta/meta_high_confidence_genes.csv", show_col_types = FALSE) %>%
  dplyr::slice_head(n = 30)
p3 <- ggplot(meta_tbl, aes(x = meta_logFC, y = reorder(gene, meta_logFC), color = meta_FDR < 0.05)) +
  geom_point() +
  theme_minimal(base_size = 11) +
  labs(title = "Figure 3. High-confidence meta-analysis genes", x = "Meta logFC", y = NULL)

save_plot_pdf(p3, "results/figures/Figure_3_meta_analysis_summary.pdf", width = 8, height = 7)

# Figure 4: pathway consensus heatmap
path_long <- readr::read_csv("data/processed/pathways/hallmark_all_studies_long.csv", show_col_types = FALSE)
path_top <- readr::read_csv("data/processed/pathways/hallmark_consensus_summary.csv", show_col_types = FALSE) %>%
  dplyr::slice_head(n = 20) %>% dplyr::pull(pathway)
mat <- path_long %>%
  dplyr::filter(pathway %in% path_top) %>%
  dplyr::select(pathway, study, logFC) %>%
  tidyr::pivot_wider(names_from = study, values_from = logFC) %>%
  as.data.frame()
rownames(mat) <- mat$pathway
mat$pathway <- NULL
pdf("results/figures/Figure_4_pathway_consensus_heatmap.pdf", width = 8, height = 10)
pheatmap::pheatmap(as.matrix(mat), fontsize_row = 8, main = "Figure 4. Consensus Hallmark shifts")
dev.off()

# Figure 5: module scores
mod_files <- list.files("data/processed/modules", pattern = "_module_scores\\.csv$", full.names = TRUE)
mod_all <- purrr::map_dfr(mod_files, readr::read_csv, show_col_types = FALSE)
mod_primary <- mod_all %>% dplyr::filter(disease_group %in% c("ND", "T2D"))
p5 <- ggplot(mod_primary, aes(x = disease_group, y = IsletDysfunctionScore, fill = disease_group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.12, alpha = 0.6) +
  facet_wrap(~study, scales = "free_y") +
  theme_minimal(base_size = 11) +
  labs(title = "Figure 5. Islet dysfunction module score", x = NULL, y = "Score")

save_plot_pdf(p5, "results/figures/Figure_5_module_scores.pdf", width = 10, height = 7)

message2("10_figures_tables complete. Add manual figure polishing before submission.")
